id: IA4FAD924
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:32:58+00:00'
last_modified: '2022-06-07T14:14:35.153794+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC381
  title: 'ཆོས་བཞིས་བསྟན་པའི་སྒོ་བསྡུ་བའི་ཚིགས་སུ་བཅད་པ་རྗེ་སྒམ་པོ་པའི་ཞལ་གྱི་གདམས་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    419F:
      image_group_id: I2PD18932
      title: ''
      total_pages: 292
      order: 1
      base_file: 419F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
