id: P001734
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:17:26.856463
source_metadata:
  id: bdr:W1AC381
  title: 'ཆོས་བཞིས་བསྟན་པའི་སྒོ་བསྡུ་བའི་ཚིགས་སུ་བཅད་པ་རྗེ་སྒམ་པོ་པའི་ཞལ་གྱི་གདམས་པ། '
  author: ''
  volumes:
    62659ec5ea44480291a267db4da15220:
      image_group_id: I2PD18932
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
